### ISSUE TITLE
掉落物设置指向数据就会报错,不掉落

### ISSUE THREAD

**Issue by moyu-777** [Neige7/NeigeItems-Kotlin#1]
mm版本 4.10
`[16:11:27 WARN]: [NeigeItems] Plugin NeigeItems v1.2.11 generated an exception while executing task 860
java.lang.IndexOutOfBoundsException: toIndex = 6
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1012) ~[?:1.8.0_152]
        at java.util.ArrayList.subList(ArrayList.java:1004) ~[?:1.8.0_152]
        at kotlin1610.collections.CollectionsKt___CollectionsKt.slice(_Collections.kt:864) ~[?:?]
        at pers.neige.neigeitems.hook.mythicmobs.impl.MythicMobsHookerImpl$deathListener$1$1.invoke(MythicMobsHookerImpl.kt:179) ~[?:?]
        at pers.neige.neigeitems.hook.mythicmobs.impl.MythicMobsHookerImpl$deathListener$1$1.invoke(MythicMobsHookerImpl.kt:112) ~[?:?]
        at pers.neige.neigeitems.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Comment by Neige7** [comment]
使用1.2.19+版本的NeigeItems
