### ISSUE TITLE
TrMenu Incompatibility

### ISSUE THREAD

**Issue by Adriianh** [Neige7/NeigeItems-Kotlin#3]
NeigeItems doesn't load when TrMenu is installed.

```
[21:27:10 ERROR]: Could not load 'plugins/NeigeItems.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.LinkageError: loader constraint violation: loader 'NeigeItems.jar' @6ee05e9c wants to load class com.electronwill.nightconfig.core.io.ParsingMode. A different class with the same name was previously loaded by 'TrMenu.jar' @4d2a0efa. (com.electronwill.nightconfig.core.io.ParsingMode is in unnamed module of loader 'TrMenu.jar' @4d2a0efa, parent loader java.net.URLClassLoader @5c29bfd)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:158) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:417) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:325) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:468) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.LinkageError: loader constraint violation: loader 'NeigeItems.jar' @6ee05e9c wants to load class com.electronwill.nightconfig.core.io.ParsingMode. A different class with the same name was previously loaded by 'TrMenu.jar' @4d2a0efa. (com.electronwill.nightconfig.core.io.ParsingMode is in unnamed module of loader 'TrMenu.jar' @4d2a0efa, parent loader java.net.URLClassLoader @5c29bfd)
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:230) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:131) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
        at pers.neige.neigeitems.taboolib.library.reflex.ClassAnalyser.analyseByReflection(ClassAnalyser.kt:28) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.library.reflex.ClassAnalyser.analyse(ClassAnalyser.kt:19) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:69) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.library.reflex.ReflexClass$Companion.of$default(ReflexClass.kt:65) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.common.io.Project1Kt.getInstance(Project1.kt:59) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:82) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:57) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:153) ~[NeigeItems.jar:?]
        at pers.neige.neigeitems.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:37) ~[NeigeItems.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:154) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more
```

**Comment by Adriianh** [comment]
It seems to be incompatibility with another plugin (Carbon), TrMenu doesn't load either.
[Carbon](https://github.com/Hexaoxide/Carbon)

**Comment by Neige7** [comment]
Try version 1.5.5. NeigeItems and TrMenu use the same library TabooLib. if 1.5.5 still does not load, then TabooLib may be the cause of the problem. (Incidentally, the wiki address has been changed to https://neige7.github.io/NeigeItems-Wiki-Docsify/)

**Comment by Adriianh** [comment]
Thanks, I'll try. It's probably a TabooLib or Carbon problem, since having the Carbon plugin, TrMenu doesn't load either.
