### ISSUE TITLE
不支持JAVA8

### ISSUE THREAD

**Issue by zhibeigg** [Neige7/NeigeItems-Kotlin#4]
[02:49:07] [Server thread/ERROR]: Could not load 'plugins\NeigeItems-1.6.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/openjdk/nashorn/api/scripting/NashornScriptEngineFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.UnsupportedClassVersionError: org/openjdk/nashorn/api/scripting/NashornScriptEngineFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_332]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_332]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_332]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_332]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_332]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_332]
	at java.lang.Class.getDeclaredFields(Class.java:1916) ~[?:1.8.0_332]
	at pers.neige.neigeitems.taboolib.library.reflex.ClassAnalyser.analyseByReflection(ClassAnalyser.kt:27) ~[?:?]
	at pers.neige.neigeitems.taboolib.library.reflex.ClassAnalyser.analyse(ClassAnalyser.kt:19) ~[?:?]
	at pers.neige.neigeitems.taboolib.library.reflex.ReflexClass$Companion.of(ReflexClass.kt:69) ~[?:?]
	at pers.neige.neigeitems.taboolib.library.reflex.ReflexClass$Companion.of$default(ReflexClass.kt:65) ~[?:?]
	at pers.neige.neigeitems.taboolib.common.io.Project1Kt.getInstance(Project1.kt:79) ~[?:?]
	at pers.neige.neigeitems.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:92) ~[?:?]
	at pers.neige.neigeitems.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:63) ~[?:?]
	at pers.neige.neigeitems.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:172) ~[?:?]
	at pers.neige.neigeitems.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:54) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	... 6 more

**Comment by Neige7** [comment]
加QQ群，把测试用的服务端压缩一下发给我。出现这个报错是因为你服务端的某个插件将openjdk的nashorn打包进了插件里。

**Comment by Neige7** [comment]
使用1.6.5版本
